insert_s_paper_sql = "insert into s_paper(p_type,p_title,p_report_url,p_do_url) value (%s, %s, %s, %s);"
insert_s_subject_sql = "insert into s_subject(paper_id,sub_no,sub_title) value (%s, %s, %s);"
insert_s_pic_sql = "insert into s_pic(pic_url) value (%s);"
insert_s_sub_pic_sql = "insert into s_sub_pic(sub_id,pic_id) value (%s, %s);"
insert_s_choose_sql = "insert into s_choose(sub_id,ch_a,ch_b,ch_c,ch_d,ch_true,ch_my) value (%s, %s, %s, %s, %s, %s, %s);"
insert_s_sub_ch_sql = "insert into s_sub_ch(sub_id,ch_id) value (%s, %s);"
insert_s_sub_ref_pic_sql = "insert into s_sub_ref_pic(sub_id,pic_id) value (%s, %s)"
update_s_subject_sql = "update s_subject set sub_tag = %s , sub_info = %s , sub_ref = %s where id = %s"
